#create_account()
#get_account_details()
#check_balance()
#update_balance()
#delete_account()
def create_account():
    name = input("Enter name: ")
    pin = input("Enter PIN: ")
    balance = float(input("Enter initial balance(enter if no balance yet): "))
    money-withd= int(input("enter money to be withdrawn(enter if no money to be withdrawn): "))

def get_accout_details():
    name = input("Enter full name: ")
    age = int(input("Enter age: "))
    phone = input("Enter phone number: ")
    email = input("Enter email: ")
    address = input("Enter your full address: ")
    account_type = input("Savings or Current: ")
    deposit = float(input("Initial deposit: "))
    username = input("Create username: ")
    pin = input("Create 4-digit PIN: ")
