#create_account()
#get_account_details()
#check_balance()
#update_balance()
#delete_account()
def create_account():
    name = input("Enter name: ")
    pin = input("Enter PIN: ")
    balance = float(input("Enter initial balance: "))
    money-withd= int(input("enter money to be withdrawn"))